baseURL = "https://r-toulouse.netlify.app/"
languageCode = "fr-fr"
title = "R Toulouse"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
# googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true

[params]
    author = "R Toulouse"
    description = "R User Group Toulouse"
    description_fr = "Groupe d'utilisatrices et d'utilisateurs de R de Toulouse"
    githubUsername = "R-Toulouse"
    accent = "#FF5599"
    profilePic = "/img/logo.svg"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["R", "go", "haskell", "kotlin", "scala", "swift"]
    copyright = "Propulsé par [Blogdown](https://github.com/rstudio/blogdown), [Hugo](https://gohugo.io), [Minimal](https://github.com/calintat/minimal), [GitHub](https://github.com/) et [netlify](https://www.netlify.com/)."
    favicon = "/img/logo.svg"
    dateFormat = "2006-01-02"


[[menu.main]]
    url = "/"
    name = "Accueil"
    weight = 1

[[menu.main]]
    url = "/evenements/"
    name = "Évènements"
    weight = 2

[[menu.main]]
    url = "/a-propos/"
    name = "À propos"
    weight = 3

[[menu.main]]
    url = "/code-de-conduite/"
    name = "Code de conduite"
    weight = 4


# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://twitter.com/RUG_Toulouse"
    name = "twitter"
    weight = 1

[[menu.icon]]
    url = "https://github.com/R-Toulouse"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://r-grrr.slack.com"
    name = "slack"
    weight = 3

[[menu.icon]]
    url = "https://groupes.renater.fr/sympa/info/r-toulouse"
    name = "envelope-o"
    weight = 4

[[menu.icon]]
    url = "https://www.youtube.com/@r-toulouserug6316"
    name = "youtube"
    weight = 5
