---
title: Rencontre de Novembre 2019
author: Guillaume Devailly
date: '2019-10-28'
slug: rencontre-de-novembre-2019
categories:
  - Rencontres
tags:
  - R Markdown
---

La prochaine du groupe des utilisatrices et utilisateurs de R de Toulouse est prévue le **lundi 18 novembre 2019** de **17h00 à 18h30**.
Attention, nous avons dû changer la date par rapport à ce qui avait été précédemment annoncé.

Cette rencontre aura exceptionnellement lieu à l’amphithéâtre Marc Ridet du **Centre INRA d'Auzeville** (24 chemin de Borde-Rouge, 31326 Auzeville) :

```{r plan, echo=FALSE}
library(leaflet)
leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lat = 43.52783, lng = 1.50011, popup = "Marc Ridet, INRA Auzeville")
```

Le centre est accessible en transport en commun : métro ligne B jusqu'à Ramonville, puis Linéo 6 jusqu'à l'arrêt INRA.
L’amphithéâtre est situé à côté de l'accueil du centre. 

---

## Programme

[Nathalie Vialaneix](http://www.nathalievialaneix.eu/) nous présentera **la famille \*down (R markdown & co.)** :

Vous rêvez de tout pouvoir faire sous R ? Vos rapports mais
aussi vos livres, vos sites web, vos documentations, vos posters, ... ?
Cet exposé est fait pour vous ! Nathalie tentera d'y présenter les
différents membres de la famille Rmarkdown et de vous montrer quelques
options utiles pour leur utilisation.
Cette présentation ne vous apprendra malheureusement pas à vous faire
servir un café par R. 

---

Ces rencontres sont gratuites, ouvertes à toutes et tous, académiques, professionnels et amateurs, débutants ou confirmés.
N'hésitez pas à diffuser l'annonce autour de vous ! Notamment en placardant [cette affiche](/poster/poster_2019_11.pdf) à des endroits stratégiques.

