---
title: Rencontre de Février 2019
author: Guillaume Devailly
date: '2019-01-31'
slug: rencontre-de-fevrier-2019
categories:
  - Rencontres
tags:
  - Rencontres
---

La rencontre de Décembre 2018 du groupe des utilisatrices et utilisateurs de R de Toulouse est prévue le **jeudi 14 février 2019** de **17h30 à 18h30**,
à l'**amphithéâtre Riquet de l'Institut National des Sciences Appliquées (INSA) de Toulouse** (métro ligne B, Faculté de Pharmacie) :

```{r plan3, echo=FALSE}
library(leaflet)
leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lat = 43.57207, lng = 1.46610, popup = "Amphi Riquet, INSA")
```

Attention, il ne s'agit d'une **autre salle que la dernière fois**. L'amphithéatre est au rez-de-chaussé du bâtiment A1 de l'INSA.

---

## Programme

**Vitesses d’exécution dans R : comparaisons de base `R`, `dplyr` et `data.table`**, par Antoine Sireyjol ([site personnel](https://antoinesir.rbind.io), [twitter](https://twitter.com/AntoineSyr))

Cette présentation a pour but de comparer les différentes options que sont base R, dplyr et data.table en terme de temps d’exécution. Elle présentera pour cela quelques instructions classiquement utilisées dans R déclinées pour chacune de ces options. Quelques astuces d’optimisation seront également présentées.

Antoine Sireyjol est statisticien freelance après 4 années au sein du service statistique du Ministère des Solidarités et de la Santé, la Drees. Il travaille en ce moment sur la migration d’outils de la Drees de SAS vers R.


**`RJags`, se lancer dans les statistiques Bayésiennes avec R**, par Sonia Eynard

JAGS (Just Another Gibs Sampler) est implémenté sous la forme d'un package R pour permettre l'analyse Bayésienne de données. Nous verrons ensemble comment installer et utiliser ce package sur des exemple simples pour ce lancer dans l'analyse Bayésienne. Voir 
[ici](https://channel9.msdn.com/Events/useR-international-R-User-conferences/useR-International-R-User-2017-Conference/Introduction-to-Bayesian-inference-with-JAGS),
[ici](https://www.rdocumentation.org/packages/rjags/versions/4-8),
ou [là](https://jeromyanglim.blogspot.com/2012/04/getting-started-with-jags-rjags-and.html).


---

Vous pouvez dès à présent soumettre une proposition pour un oral ou un poster pour la conférence
[UseR! 2019](http://user2019.r-project.org/abstracts/) qui se tiendra du 9 au 12 Juillet à Toulouse.

User! 2019 [organise aussi](http://user2019.r-project.org/datathon/) un *Datathon* dont le gagnant pourra venir gratuitement à la conférence.
Les rapports sont à rendre avant le 1er Mars 2019.

Toulouse DataViz organise un nouveau Hackathon autour de la visualisation de données. [Inscrivez-vous](http://toulouse-dataviz.fr/hackaviz-2019-2)
vite !

---

**Nous cherchons des oratrices ou orateurs pour les prochains évènements**, pour y assurer une présentation de 20 minutes, suivies de 10 minutes d'échanges avec l'audience.
Tous les sujets sont les bienvenus, en espérant pouvoir organiser une session introductive (par exemple à `R` en général, au `tidyverse`, à `R markdown`, aux bonnes pratiques, etc.) et une session plus spécialisée (présentation d'un nouveau *package*, introduction au développement de *packages*, `shiny`, comment R est utilisé dans votre groupe, etc.).

**Nous avons besoins de vous !** Si vous êtes volontaire, merci de nous contacter (par mail : rug.toulouse[at]gmail.com ou twitter à votre convenance, liens en haut à gauche de la page), avec un titre et un petit résumé de votre présentation.

---

Ces rencontres sont gratuites, ouvertes à toutes et tous, académiques, professionnels et amateurs, débutants ou confirmés.

N'hésitez pas à diffuser l'annonce autour de vous.

