---
title: Rencontre du 31 mars 2022
author: Guillaume Devailly
date: '2022-03-01'
slug: []
categories:
    - Rencontres
tags:
    - Rencontres
    - broom
    - purrr
    - furrr
    - Statistiques
---

La prochaine rencontre de R-Toulouse est prévue par visio le 
**31 mars 2022** de **16h00 à 17h00** sur la plateforme de
visioconférence **Zoom**.

---

## Programme

**{broom}, {purrr}, {furrr} : automatiser la modélisation statistique dans le tidyverse**,
par [Bertrand Servin](https://twitter.com/BertrandServin) (INRAE) et Guilhem Huau.

Avec l’augmentation des volumes de données, il est très courant de devoir estimer 
un même modèle statistique sur différents groupes d’observation. 
Par exemple estimer les effets de différentes traitements sur
l’expression de chaque gène dans le génome.
Dans cette session, nous montrerons comment effectuer ces tâches dans la grammaire du tidyverse,
les faire fonctionner en parallèle pour optimiser les temps de calcul
et récupérer les résultats des modèles pour faciliter leur interprétation.

---

## Informations de connection

Participer à la réunion Zoom: jeudi 31 mars 2022 de 16h00 à 17h00

[inrae-fr.zoom.us/j/6644865679](https://inrae-fr.zoom.us/j/6644865679)  
ID de réunion : 664 486 5679

La réunion sera enregistrée.
